// <auto-generated />
// Generated by LocalizationDataExporterDrawer. Do not edit manually.
using System.Collections.Generic;
using Mu3Library.Localization.Data;

namespace Mu3Library.Sample.Template.Localization
{
    public static class LocalizationTableKeys
    {
        public static readonly LocalizationTableKeysTestStringTable TestStringTable = LocalizationTableKeysTestStringTable.Instance;

        public static readonly IReadOnlyDictionary<string, TableData> All = new Dictionary<string, TableData>
        {
            { TestStringTable.Name, TestStringTable },
        };
    }
}
