// <auto-generated />
// Generated by LocalizationDataExporterDrawer. Do not edit manually.
using System.Collections.Generic;
using Mu3Library.Localization.Data;

namespace Mu3Library.Sample.Template.Localization
{
    public sealed class LocalizationTableKeysTestStringTable : TableData
    {
        private const string TableName = "TestStringTable";

        private static readonly EntryData _hello = new EntryData(TableName, "hello", "909386731520");
        public readonly EntryData Hello = _hello;
        private static readonly EntryData _test02Test = new EntryData(TableName, "test-02-test", "37107648355389440");
        public readonly EntryData Test02Test = _test02Test;

        private static readonly IReadOnlyDictionary<string, LocaleData> _tableLocales = new Dictionary<string, LocaleData>
        {
            { LocalizationTableKeysLocales.En.Code, LocalizationTableKeysLocales.En },
            { LocalizationTableKeysLocales.Ja.Code, LocalizationTableKeysLocales.Ja },
            { LocalizationTableKeysLocales.Ko.Code, LocalizationTableKeysLocales.Ko },
        };

        private static readonly IReadOnlyDictionary<string, EntryData> _tableEntries = new Dictionary<string, EntryData>
        {
            { _hello.Key, _hello },
            { _test02Test.Key, _test02Test },
        };

        public static readonly LocalizationTableKeysTestStringTable Instance = new LocalizationTableKeysTestStringTable();

        internal LocalizationTableKeysTestStringTable() : base(
            TableName,
            _tableLocales,
            _tableEntries)
        {
        }
    }
}
