// <auto-generated />
// Generated by LocalizationDataExporterDrawer. Do not edit manually.
using System.Collections.Generic;
using Mu3Library.Localization.Data;

namespace Mu3Library.Sample.Template.Localization
{
    public static class LocalizationTableKeysLocales
    {
        public static readonly LocaleData En = new LocaleData("en", "English", "English");
        public static readonly LocaleData Ja = new LocaleData("ja", "Japanese", "日本語");
        public static readonly LocaleData Ko = new LocaleData("ko", "Korean", "한국어");

        public static readonly IReadOnlyDictionary<string, LocaleData> All = new Dictionary<string, LocaleData>
        {
            { En.Code, En },
            { Ja.Code, Ja },
            { Ko.Code, Ko },
        };
    }
}
