// <auto-generated />
// Generated by AddressableGroupDataExporterDrawer. Do not edit manually.
using System.Collections.Generic;
using Mu3Library.Addressable.Data;

namespace Mu3Library.Sample.Template.Addressable
{
    public sealed class AddressableGroupKeysLocalizationLocales : GroupData
    {
        public sealed class EnglishEnLocaleEntry : EntryData
        {

            public EnglishEnLocaleEntry() : base(
                "English (en)",
                "English (en)",
                new string[] { AddressableGroupKeysLabels.BaseDownload, AddressableGroupKeysLabels.Locale }
            )
            {
            }
        }

        public sealed class JapaneseJaLocaleEntry : EntryData
        {

            public JapaneseJaLocaleEntry() : base(
                "Japanese (ja)",
                "Japanese (ja)",
                new string[] { AddressableGroupKeysLabels.BaseDownload, AddressableGroupKeysLabels.Locale }
            )
            {
            }
        }

        public sealed class KoreanKoLocaleEntry : EntryData
        {

            public KoreanKoLocaleEntry() : base(
                "Korean (ko)",
                "Korean (ko)",
                new string[] { AddressableGroupKeysLabels.BaseDownload, AddressableGroupKeysLabels.Locale }
            )
            {
            }
        }


        private static readonly EnglishEnLocaleEntry _englishEnLocale = new EnglishEnLocaleEntry();
        public readonly EnglishEnLocaleEntry EnglishEnLocale = _englishEnLocale;
        private static readonly JapaneseJaLocaleEntry _japaneseJaLocale = new JapaneseJaLocaleEntry();
        public readonly JapaneseJaLocaleEntry JapaneseJaLocale = _japaneseJaLocale;
        private static readonly KoreanKoLocaleEntry _koreanKoLocale = new KoreanKoLocaleEntry();
        public readonly KoreanKoLocaleEntry KoreanKoLocale = _koreanKoLocale;

        private static readonly IReadOnlyList<EntryData> _groupEntries = new EntryData[]
        {
            _englishEnLocale,
            _japaneseJaLocale,
            _koreanKoLocale,
        };

        private static readonly IReadOnlyList<string> _groupLabels = new string[]
        {
            AddressableGroupKeysLabels.BaseDownload,
            AddressableGroupKeysLabels.Locale,
        };

        public static readonly AddressableGroupKeysLocalizationLocales Instance = new AddressableGroupKeysLocalizationLocales();

        internal AddressableGroupKeysLocalizationLocales() : base(
            "Localization-Locales",
            _groupEntries,
            _groupLabels)
        {
        }
    }
}
