// <auto-generated />
// Generated by AddressableGroupDataExporterDrawer. Do not edit manually.
using System.Collections.Generic;
using Mu3Library.Addressable.Data;

namespace Mu3Library.Sample.Template.Addressable
{
    public sealed class AddressableGroupKeysLocalizationStringTablesJapaneseJa : GroupData
    {
        public sealed class TestStringTableJaStringTableEntry : EntryData
        {

            public TestStringTableJaStringTableEntry() : base(
                "TestStringTable_ja",
                "TestStringTable_ja",
                new string[] { AddressableGroupKeysLabels.BaseDownload, AddressableGroupKeysLabels.LocaleJa }
            )
            {
            }
        }


        private static readonly TestStringTableJaStringTableEntry _testStringTableJaStringTable = new TestStringTableJaStringTableEntry();
        public readonly TestStringTableJaStringTableEntry TestStringTableJaStringTable = _testStringTableJaStringTable;

        private static readonly IReadOnlyList<EntryData> _groupEntries = new EntryData[]
        {
            _testStringTableJaStringTable,
        };

        private static readonly IReadOnlyList<string> _groupLabels = new string[]
        {
            AddressableGroupKeysLabels.BaseDownload,
            AddressableGroupKeysLabels.LocaleJa,
        };

        public static readonly AddressableGroupKeysLocalizationStringTablesJapaneseJa Instance = new AddressableGroupKeysLocalizationStringTablesJapaneseJa();

        internal AddressableGroupKeysLocalizationStringTablesJapaneseJa() : base(
            "Localization-String-Tables-Japanese (ja)",
            _groupEntries,
            _groupLabels)
        {
        }
    }
}
