// <auto-generated />
// Generated by AddressableGroupDataExporterDrawer. Do not edit manually.
using System.Collections.Generic;
using Mu3Library.Addressable.Data;

namespace Mu3Library.Sample.Template.Addressable
{
    public sealed class AddressableGroupKeysTestScene : GroupData
    {
        public sealed class SampleAddressablesSceneAssetEntry : EntryData
        {

            public SampleAddressablesSceneAssetEntry() : base(
                "Sample_Addressables",
                "Sample_Addressables",
                new string[] { AddressableGroupKeysLabels.TestScene }
            )
            {
            }
        }

        public sealed class SampleAddressablesAdditiveSceneAssetEntry : EntryData
        {

            public SampleAddressablesAdditiveSceneAssetEntry() : base(
                "Sample_AddressablesAdditive",
                "Sample_AddressablesAdditive",
                new string[] { AddressableGroupKeysLabels.TestScene }
            )
            {
            }
        }


        private static readonly SampleAddressablesSceneAssetEntry _sampleAddressablesSceneAsset = new SampleAddressablesSceneAssetEntry();
        public readonly SampleAddressablesSceneAssetEntry SampleAddressablesSceneAsset = _sampleAddressablesSceneAsset;
        private static readonly SampleAddressablesAdditiveSceneAssetEntry _sampleAddressablesAdditiveSceneAsset = new SampleAddressablesAdditiveSceneAssetEntry();
        public readonly SampleAddressablesAdditiveSceneAssetEntry SampleAddressablesAdditiveSceneAsset = _sampleAddressablesAdditiveSceneAsset;

        private static readonly IReadOnlyList<EntryData> _groupEntries = new EntryData[]
        {
            _sampleAddressablesSceneAsset,
            _sampleAddressablesAdditiveSceneAsset,
        };

        private static readonly IReadOnlyList<string> _groupLabels = new string[]
        {
            AddressableGroupKeysLabels.TestScene,
        };

        public static readonly AddressableGroupKeysTestScene Instance = new AddressableGroupKeysTestScene();

        internal AddressableGroupKeysTestScene() : base(
            "TestScene",
            _groupEntries,
            _groupLabels)
        {
        }
    }
}
